#ifndef TOWNSHIP_DATA_H
#define TOWNSHIP_DATA_H

#include "township.h"

/* ── Factory IDs ── */
enum {
    FAC_FIELD,
    FAC_FEED_MILL,
    FAC_DAIRY,
    FAC_BAKERY,
    FAC_SUGAR_FACTORY,
    FAC_TEXTILE_FACTORY,
    FAC_COW,
    FAC_CHICKEN,
    FAC_SHEEP,
    FAC_BEE,
    FAC_PIG,
    FAC_DUCK,
    FAC_OTTER,
    FAC_MUSHROOM_FARM,
    FAC_FOOD_PROCESSING,
    FAC_PASTRY_FACTORY,
    FAC_ICE_CREAM_FACTORY,
    FAC_RUBBER_FACTORY,
    FAC_PAPER_FACTORY,
    FAC_FAST_FOOD,
    FAC_SNACK_FACTORY,
    FAC_TAILOR_SHOP,
    FAC_JAM_FACTORY,
    FAC_ASIAN_RESTAURANT,
    FAC_JEWELRY_STORE,
    FAC_SHOE_FACTORY,
    FAC_FURNITURE_FACTORY,
    FAC_STATIONERY_FACTORY,
    FAC_MEXICAN_RESTAURANT,
    FAC_CANDY_FACTORY,
    FAC_HOUSEHOLD_GOODS,
    FAC_PLASTICS_FACTORY,
    FAC_BAG_FACTORY,
    FAC_GRILL_FACTORY,
    FAC_PERFUME_FACTORY,
    FAC_BEVERAGE_FACTORY,
    FAC_CAKE_FACTORY,
    FAC_HOT_DOG_FACTORY,
    FAC_FRENCH_RESTAURANT,
    FAC_COFFEE_FACTORY,
    FAC_DOWN_FEATHER_FACTORY,
    FAC_DOLL_FACTORY,
    FAC_PET_SUPPLY_FACTORY,
    FAC_VEGAN_CAFE,
    FAC_FESTIVITIES_FACTORY,
    FAC_GARDENING_SUPPLIES,
    FAC_ITALIAN_RESTAURANT,
    FAC_BOUQUET_FACTORY,
    FAC_KITCHENWARE_FACTORY,
    FAC_MUSIC_FACTORY,
    FAC_TEA_FACTORY,
    FAC_FRUTUS_ISLE,
    FAC_OLIVIA_ISLE,
    FAC_TROPICA_ISLE,
    FAC_FISHERMANS_ISLE,
    FAC_BONITA_ISLE,
    FAC_FOUNDRY,
    FAC_MINE,
    FAC_UNKNOWN,
    FACTORY_COUNT
};

/* ── Item IDs ── */
enum {
    /* crops (field) */
    ITEM_WHEAT,
    ITEM_CORN,
    ITEM_CARROT,
    ITEM_SUGARCANE,
    ITEM_COTTON,
    ITEM_STRAWBERRY,
    ITEM_TOMATO,
    ITEM_PINE_TREE,
    ITEM_POTATO,
    ITEM_CACAO,
    ITEM_RUBBER_TREE,
    ITEM_SILK,
    ITEM_CORK_OAK,
    ITEM_PEPPER,
    ITEM_MINT,
    ITEM_RICE,
    ITEM_ROSE,
    ITEM_JASMINE,
    ITEM_COFFEE_PLANT,
    ITEM_PEANUT_PLANT,
    ITEM_APPLE,
    ITEM_TEA_PLANT,
    ITEM_SOYBEAN,
    ITEM_LAVENDER,

    /* frutus isle (4 h) */
    ITEM_PEACH,
    ITEM_WATERMELON,
    ITEM_PLUM,

    /* olivia isle (7 h) */
    ITEM_GRAPE,
    ITEM_OLIVE,
    ITEM_KEY_LIME,

    /* tropica isle (9 h) */
    ITEM_BANANA,
    ITEM_COCONUT,
    ITEM_PINEAPPLE,

    /* fisherman's isle (8 h) */
    ITEM_FISH,
    ITEM_SHRIMP,
    ITEM_LOBSTER,

    /* bonita isle (10 h) */
    ITEM_AVOCADO,
    ITEM_MANGO,
    ITEM_ALOE,

    /* feed mill */
    ITEM_COW_FEED,
    ITEM_CHICKEN_FEED,
    ITEM_SHEEP_FEED,
    ITEM_BEE_FEED,
    ITEM_PIG_FEED,
    ITEM_SUBSTRATE,

    /* animals */
    ITEM_MILK,
    ITEM_EGG,
    ITEM_WOOL,
    ITEM_HONEYCOMBS,
    ITEM_BACON,
    ITEM_DOWN_FEATHER,
    ITEM_COLORFUL_FEATHER,
    ITEM_SEAWEED,
    ITEM_SCALLOP,
    ITEM_PEARLS,
    ITEM_MUSHROOM,

    /* dairy */
    ITEM_CREAM,
    ITEM_CHEESE,
    ITEM_BUTTER,
    ITEM_YOGURT,
    ITEM_PEACH_YOGURT,
    ITEM_TOFU,
    ITEM_PLANT_MILK,

    /* bakery */
    ITEM_BREAD,
    ITEM_COOKIES,
    ITEM_BAGEL,
    ITEM_PIZZA,
    ITEM_POTATO_BREAD,
    ITEM_BANANA_BREAD,
    ITEM_SEAFOOD_PIZZA,
    ITEM_MUSHROOM_TURNOVER,
    ITEM_APPLE_STRUDEL,

    /* sugar factory */
    ITEM_SUGAR,
    ITEM_SYRUP,
    ITEM_CARAMEL,
    ITEM_HONEY_CARAMEL,

    /* textile factory */
    ITEM_COTTON_FABRIC,
    ITEM_YARN,
    ITEM_SILK_FABRIC,
    ITEM_NYLON_THREAD,

    /* food processing plant */
    ITEM_DOUGH,
    ITEM_FROZEN_VEGETABLES,
    ITEM_DUMPLINGS,
    ITEM_SEAFOOD_MIX,
    ITEM_FROZEN_FRUIT,
    ITEM_PACKAGED_MEAL,

    /* pastry factory */
    ITEM_MUFFIN,
    ITEM_BROWNIE,
    ITEM_CUPCAKE,
    ITEM_DONUT,
    ITEM_CHEESECAKE,
    ITEM_HONEY_GINGERBREAD,
    ITEM_KEY_LIME_PIE,
    ITEM_COCONUT_MACAROON,
    ITEM_CARAMEL_APPLE,

    /* ice cream factory */
    ITEM_ICE_CREAM_CONE,
    ITEM_POPSICLE,
    ITEM_FROZEN_YOGURT,
    ITEM_ICE_CREAM_BAR,
    ITEM_MINT_CHOCO_ICE_CREAM,
    ITEM_PINEAPPLE_SORBET,
    ITEM_ROSE_SORBET,
    ITEM_PEANUT_PARFAIT,

    /* rubber factory */
    ITEM_RUBBER,
    ITEM_PLASTIC,
    ITEM_GLUE,
    ITEM_DUMBBELL,

    /* paper factory */
    ITEM_PAPER,
    ITEM_PAPER_TOWEL,
    ITEM_WALLPAPER,
    ITEM_BOOK,
    ITEM_TEA_BAGS,

    /* fast food restaurant */
    ITEM_MILKSHAKE,
    ITEM_CHEESEBURGER,
    ITEM_SANDWICH,
    ITEM_FRENCH_FRIES,
    ITEM_BAKED_POTATO,
    ITEM_FISH_BURGER,
    ITEM_FISH_AND_CHIPS,
    ITEM_PEANUT_BUTTER_CREPES,

    /* snack factory */
    ITEM_POPCORN,
    ITEM_CORN_CHIPS,
    ITEM_GRANOLA,
    ITEM_POTATO_CHIPS,
    ITEM_CANAPE,
    ITEM_GLAZED_BACON,
    ITEM_PUFFED_RICE,
    ITEM_DRIED_MUSHROOMS,
    ITEM_SALTED_PEANUTS,

    /* tailor shop */
    ITEM_SHIRT,
    ITEM_SWEATER,
    ITEM_COAT,
    ITEM_HAT,
    ITEM_DRESS,
    ITEM_SUIT,
    ITEM_TYROLEAN_HAT,
    ITEM_EVENING_GOWN,

    /* foundry */
    ITEM_BRONZE_INGOT,
    ITEM_SILVER_INGOT,
    ITEM_GOLD_INGOT,
    ITEM_PLATINUM_INGOT,

    /* mine */
    ITEM_COPPER_ORE,
    ITEM_CLAY,
    ITEM_SILVER_ORE,
    ITEM_GOLD_ORE,
    ITEM_PLATINUM_ORE,


    /* asian restaurant */
    ITEM_SUSHI_ROLL,
    ITEM_LOBSTER_SUSHI,
    ITEM_SEAWEED_SHRIMP_SALAD,
    ITEM_SCALLOP_SUSHI,
    ITEM_COCONUT_SOUP,
    ITEM_RICE_NOODLES,
    ITEM_SEA_SALAD,
    ITEM_MUSHROOM_SALAD,
    ITEM_PEANUT_SAUCE,

    /* jewelry store */
    ITEM_PENDANT,
    ITEM_RING,
    ITEM_PEARL_CHOKER,
    ITEM_EARRINGS,
    ITEM_DIADEM,
    ITEM_FEATHER_EARRINGS,

    /* shoe factory */
    ITEM_FLIP_FLOPS,
    ITEM_SANDALS,
    ITEM_SNEAKERS,
    ITEM_BOOTS,
    ITEM_HIGH_HEELED_SHOES,
    ITEM_WARM_BOOTS,

    /* furniture factory */
    ITEM_TABLE,
    ITEM_CHAIR,
    ITEM_COUCH,
    ITEM_BED,
    ITEM_FLOOR_LAMP,

    /* stationery factory */
    ITEM_ERASER,
    ITEM_STICKY_NOTES,
    ITEM_BULLETIN_BOARD,
    ITEM_HIGHLIGHTER_PEN,

    /* mexican restaurant */
    ITEM_CHILI_SAUCE,
    ITEM_BURRITO,
    ITEM_NACHOS,
    ITEM_TACO,
    ITEM_BACON_JALAPENO_POPPERS,
    ITEM_GAZPACHO,
    ITEM_CORN_SOUP,
    ITEM_MOLE_SAUCE,
    ITEM_MUSHROOM_SOUP,

    /* candy factory */
    ITEM_JELLY_BEANS,
    ITEM_TOFFEE,
    ITEM_CANDY_CANE,
    ITEM_CHOCOLATE,
    ITEM_LOLLIPOP,
    ITEM_HONEY_MARSHMALLOW,
    ITEM_MINT_CANDY,
    ITEM_JELLY_FRUIT_SLICES,
    ITEM_CHOCOLATE_BAR,
    ITEM_GREEN_TEA_CANDY,

    /* household goods factory */
    ITEM_SCRUB_BRUSH,
    ITEM_SOAP_DISPENSER,
    ITEM_CLOTHESLINE,
    ITEM_PLUNGER,
    ITEM_FEATHER_DUSTER,
    ITEM_RUBBER_GLOVES,

    /* plastics factory */
    ITEM_PLASTIC_BOTTLE,
    ITEM_TOYS,
    ITEM_BALL,
    ITEM_INFLATABLE_BOAT,
    ITEM_SHUTTLECOCK,
    ITEM_MODELING_CLAY,

    /* bag factory */
    ITEM_BACKPACK,
    ITEM_WOVEN_BAG,
    ITEM_SMALL_HANDBAG,
    ITEM_SUITCASE,
    ITEM_KIDS_BAG,

    /* grill factory */
    ITEM_QUICHE,
    ITEM_BAKED_LOBSTER,
    ITEM_BACON_AND_EGGS,
    ITEM_FRIED_FISH,
    ITEM_RICE_CASSEROLE,
    ITEM_PANCAKES_WITH_HONEY,
    ITEM_LOBSTER_OMELET,
    ITEM_GRILLED_SCALLOP,
    ITEM_ROAST_MEAT,

    /* perfume factory */
    ITEM_AROMATHERAPY_CANDLE,
    ITEM_PERFUME,
    ITEM_AIR_FRESHENER,
    ITEM_SCENTED_SOAP,
    ITEM_JASMINE_OIL,
    ITEM_LOTION,
    ITEM_FACE_MASK,
    ITEM_TOOTHPASTE,

    /* beverage factory */
    ITEM_VITAMIN_COCKTAIL,
    ITEM_GRAPE_FIZZ,
    ITEM_CHOCOLATE_SMOOTHIE,
    ITEM_WATERMELON_FRESH,
    ITEM_ICED_TEA,
    ITEM_TROPICAL_MIX,
    ITEM_APPLE_FRESH,
    ITEM_MINT_ICED_TEA,

    /* cake factory */
    ITEM_CARROT_CAKE,
    ITEM_STRAWBERRY_CAKE,
    ITEM_COFFEE_CAKE,
    ITEM_MINT_CAKE,
    ITEM_CHOCOLATE_CAKE,
    ITEM_WEDDING_CAKE,

    /* hot dog factory */
    ITEM_HOT_DOG,
    ITEM_CORN_DOG,
    ITEM_CONEY_DOG,
    ITEM_CARROT_SANDWICH,

    /* french restaurant */
    ITEM_RATATOUILLE,
    ITEM_PROFITEROLES,
    ITEM_SALADE_NICOISE,
    ITEM_BOUILLABAISSE,

    /* coffee factory */
    ITEM_ESPRESSO,
    ITEM_CAPPUCCINO,
    ITEM_CAFFE_MOCHA,
    ITEM_HOT_CHOCOLATE,
    ITEM_COCONUT_LATTE,

    /* down feather factory */
    ITEM_PILLOW,
    ITEM_PARKA,
    ITEM_DOWN_QUILT,
    ITEM_ROBE_AND_SLIPPERS,

    /* doll factory */
    ITEM_PUPPET,
    ITEM_PORCELAIN_DOLL,
    ITEM_FASHION_DOLL,
    ITEM_RAG_DOLL,

    /* pet supply factory */
    ITEM_RUBBER_BONE,
    ITEM_WIND_UP_MOUSE,
    ITEM_CAT_LITTER,
    ITEM_WATER_BOWL,
    ITEM_PET_BED,

    /* vegan cafe */
    ITEM_FALAFEL,
    ITEM_MISO_SOUP,
    ITEM_VEGAN_CHEESECAKE,
    ITEM_SOYBEAN_HUMMUS,
    ITEM_GUACAMOLE,

    /* festivities factory */
    ITEM_BALLOON,
    ITEM_COTTON_CANDY,
    ITEM_SOAP_BUBBLES,
    ITEM_LEI,
    ITEM_PINATA,

    /* gardening supplies factory */
    ITEM_GARDEN_TOOLS,
    ITEM_GARDEN_GNOME,
    ITEM_LAWN_CHAIR,
    ITEM_PLANTER,
    ITEM_GARDEN_HOSE,

    /* italian restaurant */
    ITEM_OLIVE_OIL,
    ITEM_BRUSCHETTA,
    ITEM_PASTA_ARRABIATA,
    ITEM_RAVIOLI,
    ITEM_TIRAMISU,
    ITEM_LASAGNA,

    /* bouquet factory */
    ITEM_SUMMER_BOUQUET,
    ITEM_VEGETABLE_BOUQUET,
    ITEM_WEDDING_BOUQUET,
    ITEM_CANDY_BOUQUET,
    ITEM_FLOWER_BASKET,
    ITEM_LAVENDER_BOUQUET,
    ITEM_TEA_COFFEE_BOUQUET,

    /* kitchenware factory */
    ITEM_CUP,
    ITEM_FRYING_PAN,
    ITEM_TRIVET_MAT,
    ITEM_TEAPOT,
    ITEM_CUTLERY,
    ITEM_TEA_CEREMONY_SET,

    /* music factory */
    ITEM_UKULELE,
    ITEM_SAXOPHONE,
    ITEM_DRUM,
    ITEM_ACCORDION,
    ITEM_PAN_FLUTE,

    /* tea factory */
    ITEM_BLACK_TEA,
    ITEM_JASMINE_WHITE_TEA,
    ITEM_ROSE_TEA,
    ITEM_BUTTER_TEA,
    ITEM_APPLE_TEA,
    ITEM_MILK_OOLONG_TEA,
    ITEM_CHOCOLATE_CUSTARD,

    /* jam factory */
    ITEM_STRAWBERRY_JAM,
    ITEM_PEACH_MARMALADE,
    ITEM_WATERMELON_JAM,
    ITEM_PLUM_JAM,
    ITEM_GRAPE_JELLY,
    ITEM_ROSE_JAM,
    ITEM_CARAMELIZED_MUSHROOMS,
    ITEM_PEANUT_BUTTER,
    ITEM_APPLE_JAM,

    ITEM_COUNT
};

extern const Factory g_factories[FACTORY_COUNT];
extern const Item    g_items[ITEM_COUNT];
extern const char    g_item_images[ITEM_COUNT][MAX_IMAGE_NAME];

#endif /* TOWNSHIP_DATA_H */
